#!/bin/bash

#===============================================================================
# TITLE    : gmtools
# ABSTRACT : An alias of "~/.genetic-heatmaps/terminal-interface.sh". It should
#            be located in the "~/bin" directory so that the shell recognizes
#            the "gmtools" command.
#
# AUTHOR   : Dennis Aldea <dennis.aldea@gmail.com>
# DATE     : 2017-06-28
#
# LICENCE  : MIT <https://opensource.org/licenses/MIT>
#-------------------------------------------------------------------------------
# TODO: add usage, options, and argument notes
#-------------------------------------------------------------------------------
# ALIAS PROGRESSION:
#     1. ghmtools OPERATION [OPTIONS] ARGUMENTS
#     2. ~/bin/ghmtools OPERATION [OPTIONS] ARGUMENTS
#     3. ~/.genetic-heatmaps/terminal-interface.sh OPERATION [OPTIONS] ARGUMENTS
#     4. ~/.genetic-heatmaps/${OPERATION}-interface.sh [OPTIONS] ARGUMENTS
#===============================================================================

# pass all arguments to "terminal-interface.sh"
~/.genetic-heatmaps/terminal-interface.sh "$@"
